language: cpp
dist: bionic

# addons:
#   apt:
#     sources:
#      - 
#     packages:
#      - 

before_install:
  - sudo apt-get install -y libz3-dev
addons:
  apt:
    update: true

before_script:
  - make antlr4-cpp-runtime
  - make antlr4-cpp-runtime/dist/libantlr4-runtime.a

script:
  - make generated/BSV.g4
  - make generated/BSVParser.cpp
  - make bin/bsv-parser
  - bin/bsv-parser example/ProcMemSpec.bsv

after_success:
  - echo yay!
